/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationProject;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author novad
 */
public class KetersedianMenu extends javax.swing.JFrame {

    /**
     * Creates new form KetersedianMenu
     */
    String SectionID = "";
    String SectionNumber = "";
    String SectionType = "";
    String SectionStatus = "";
    
    public KetersedianMenu() {
        initComponents();
        displayData();
        setTitle("Ketersediaan Section");
        setLocationRelativeTo(null);
        
        SectionTable.addMouseListener(new MouseAdapter(){
            DefaultTableModel model = new DefaultTableModel();
            
            @Override
            public void mouseClicked(MouseEvent e){
                int i = SectionTable.getSelectedRow();
                SectionID = (SectionTable.getValueAt(i, 0).toString());
                SectionNumber = (SectionTable.getValueAt(i, 1).toString());
                SectionType =(SectionTable.getValueAt(i, 2).toString());
                SectionStatus = (SectionTable.getValueAt(i, 3).toString());
            }
        });
    }
    
    private void displayData() {
      Connection con = Koneksi.koneksi();
      try {
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT * FROM carwash_section");
         DefaultTableModel model = new DefaultTableModel();
         model.addColumn("Section ID");
         model.addColumn("Section Number");
         model.addColumn("Section Type");
         model.addColumn("Section Status");
         
         while (rs.next()) {
            String SecId = rs.getString("Section_ID");
            String SecNumber = rs.getString("Section_Number");
            String SecType = rs.getString("Section_Type");
            String SecStatus = rs.getString("Section_Status");
            
            model.addRow(new Object[]{SecId, SecNumber, SecType, SecStatus});
         }
         SectionTable.setModel(model);
         if(stmt != null){
             stmt.close();
         }
      } catch (SQLException e) {
         System.out.println(e);
      } finally {
          Koneksi.closeConnection();
      }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KembaliKetersedian = new javax.swing.JButton();
        LogOutBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SectionTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SectionIdinput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SectionNuminput = new javax.swing.JTextField();
        SectionStainput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SectionTypeinput = new javax.swing.JComboBox<>();
        SimpanSection = new javax.swing.JButton();
        HapusSection = new javax.swing.JButton();
        EditSection = new javax.swing.JButton();
        GetSection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KETERSEDIAAN");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SECTION");

        KembaliKetersedian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ApplicationProject/R.png"))); // NOI18N
        KembaliKetersedian.setText("Kembali");
        KembaliKetersedian.setBackground(new java.awt.Color(153, 51, 255));
        KembaliKetersedian.setBorder(null);
        KembaliKetersedian.setContentAreaFilled(false);
        KembaliKetersedian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KembaliKetersedian.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        KembaliKetersedian.setForeground(new java.awt.Color(255, 255, 255));
        KembaliKetersedian.setIconTextGap(8);
        KembaliKetersedian.setMaximumSize(new java.awt.Dimension(1095, 990));
        KembaliKetersedian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliKetersedianActionPerformed(evt);
            }
        });

        LogOutBooking.setBackground(new java.awt.Color(153, 51, 255));
        LogOutBooking.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        LogOutBooking.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ApplicationProject/R__1_-removebg-preview (1).png"))); // NOI18N
        LogOutBooking.setText("LogOut");
        LogOutBooking.setBorder(null);
        LogOutBooking.setContentAreaFilled(false);
        LogOutBooking.setIconTextGap(8);
        LogOutBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(KembaliKetersedian, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogOutBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KembaliKetersedian, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        SectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Section ID", "Section Number", "Section Type", "Section Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SectionTable);

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Section ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Section Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Section Type");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Section Status");

        SectionTypeinput.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        SectionTypeinput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(SectionIdinput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(SectionNuminput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(SectionTypeinput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(SectionStainput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SectionTypeinput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SectionIdinput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SectionNuminput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SectionStainput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        SimpanSection.setBackground(new java.awt.Color(0, 153, 0));
        SimpanSection.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        SimpanSection.setForeground(new java.awt.Color(255, 255, 255));
        SimpanSection.setText("Tambah+");
        SimpanSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanSectionActionPerformed(evt);
            }
        });

        HapusSection.setBackground(new java.awt.Color(255, 51, 51));
        HapusSection.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        HapusSection.setForeground(new java.awt.Color(255, 255, 255));
        HapusSection.setText("Hapus");
        HapusSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusSectionActionPerformed(evt);
            }
        });

        EditSection.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        EditSection.setText("Edit");
        EditSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSectionActionPerformed(evt);
            }
        });

        GetSection.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        GetSection.setText("Get Data");
        GetSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetSectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SimpanSection, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(EditSection, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GetSection, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HapusSection, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanSection, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HapusSection, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditSection, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetSection, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliKetersedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliKetersedianActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliKetersedianActionPerformed

    private void LogOutBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBookingActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBookingActionPerformed

    private void SimpanSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanSectionActionPerformed
        // TODO add your handling code here:
         Connection con = Koneksi.koneksi();
        if (evt.getSource() == SimpanSection) {
            String id = SectionIdinput.getText();
            String number = SectionNuminput.getText();
            String type = SectionTypeinput.getSelectedItem().toString();
            String status = SectionStainput.getText();
            
             try{
                PreparedStatement st = con.prepareStatement("INSERT INTO carwash_section(Section_ID, Section_Number, "
                        + "Section_Type, Section_Status) "
                        + "VALUES(?, ?, ?, ?)");
                st.setString(1, id);
                st.setString(2, number);
                st.setString(3, type);
                st.setString(4, status);
                st.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data inserted successfully!", "Insert Success", JOptionPane.INFORMATION_MESSAGE); 
                if(st != null){
                   st.close(); 
                }
             } catch(SQLException ex){
                 JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Insert Error", JOptionPane.ERROR_MESSAGE);
             } finally {
                 Koneksi.closeConnection();
             }
             
             displayData();
            SectionIdinput.setText("");
            SectionNuminput.setText("");
            SectionTypeinput.setSelectedIndex(0);   
            SectionStainput.setText("");
        }
    }//GEN-LAST:event_SimpanSectionActionPerformed

    private void HapusSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusSectionActionPerformed
        // TODO add your handling code here:\
        Connection con = Koneksi.koneksi();
        try{
            PreparedStatement stmt = con.prepareStatement("DELETE FROM carwash_section WHERE Section_ID = ?");
            stmt.setString(1, SectionID);
            int rowDelete = stmt.executeUpdate();
            if(rowDelete > 0){
                JOptionPane.showMessageDialog(null, "Row deleted successfully.");
            } else {
            JOptionPane.showMessageDialog(null, "Row not found.");
            }
            if(stmt != null){
                stmt.close();
            }
        } catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "Error deleting row: " + ex.getMessage());
        } finally{
            Koneksi.closeConnection();
        }
        
        displayData();
        SectionIdinput.setText("");
        SectionNuminput.setText("");
        SectionTypeinput.setSelectedIndex(0);   
        SectionStainput.setText("");
    }//GEN-LAST:event_HapusSectionActionPerformed

    private void GetSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetSectionActionPerformed
        // TODO add your handling code here:
        SectionIdinput.setText(SectionID);
        SectionNuminput.setText(SectionNumber);
        if(SectionType.equalsIgnoreCase("Mobil")){
         SectionTypeinput.setSelectedIndex(0);   
        } else if (SectionType.equalsIgnoreCase("Motor")){
            SectionTypeinput.setSelectedIndex(1);
        }
        SectionStainput.setText(SectionStatus);
        
    }//GEN-LAST:event_GetSectionActionPerformed

    private void EditSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSectionActionPerformed
        // TODO add your handling code here:
         Connection con = Koneksi.koneksi();
        if (evt.getSource() == EditSection) {
            String id = SectionIdinput.getText();
            String number = SectionNuminput.getText();
            String type = SectionTypeinput.getSelectedItem().toString();
            String status = SectionStainput.getText();
            
             try{
                PreparedStatement st = con.prepareStatement("UPDATE carwash_section SET Section_ID=?, Section_Number=?, "
                        + "Section_Type=?, Section_Status=? WHERE Section_ID=? ");
                st.setString(1, id);
                st.setString(2, number);
                st.setString(3, type);
                st.setString(4, status);
                st.setString(5, id);
                
                st.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data inserted successfully!", "Insert Success", JOptionPane.INFORMATION_MESSAGE); 
                if(st != null){
                   st.close(); 
                }
             } catch(SQLException ex){
                 JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Insert Error", JOptionPane.ERROR_MESSAGE);
             } finally {
                 Koneksi.closeConnection();
             }
             
             displayData();
            SectionIdinput.setText("");
            SectionNuminput.setText("");
            SectionTypeinput.setSelectedIndex(0);   
            SectionStainput.setText("");
        }
    }//GEN-LAST:event_EditSectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetersedianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetersedianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetersedianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetersedianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new KetersedianMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditSection;
    private javax.swing.JButton GetSection;
    private javax.swing.JButton HapusSection;
    private javax.swing.JButton KembaliKetersedian;
    private javax.swing.JButton LogOutBooking;
    private javax.swing.JTextField SectionIdinput;
    private javax.swing.JTextField SectionNuminput;
    private javax.swing.JTextField SectionStainput;
    private javax.swing.JTable SectionTable;
    private javax.swing.JComboBox<String> SectionTypeinput;
    private javax.swing.JButton SimpanSection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
