/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApplicationProject;

import java.awt.Color;

/**
 *
 * @author novad
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        setBackground(Color.white);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Main Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainMenuLabel = new javax.swing.JLabel();
        BookingMenu = new javax.swing.JButton();
        KetersediaanMenu = new javax.swing.JButton();
        MemberMenu = new javax.swing.JButton();
        KeluarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(193, 154, 107));

        MainMenuLabel.setFont(new java.awt.Font("Times New Roman", 3, 28)); // NOI18N
        MainMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLabel.setText("MAIN MENU");

        BookingMenu.setBackground(new java.awt.Color(0, 0, 0));
        BookingMenu.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        BookingMenu.setForeground(new java.awt.Color(255, 255, 255));
        BookingMenu.setText("Booking");
        BookingMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BookingMenu.setBorderPainted(false);
        BookingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingMenuActionPerformed(evt);
            }
        });

        KetersediaanMenu.setBackground(new java.awt.Color(0, 0, 0));
        KetersediaanMenu.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        KetersediaanMenu.setForeground(new java.awt.Color(255, 255, 255));
        KetersediaanMenu.setText("Ketersediaan");
        KetersediaanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KetersediaanMenuActionPerformed(evt);
            }
        });

        MemberMenu.setBackground(new java.awt.Color(0, 0, 0));
        MemberMenu.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        MemberMenu.setForeground(new java.awt.Color(255, 255, 255));
        MemberMenu.setText("Daftar Member");
        MemberMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberMenuActionPerformed(evt);
            }
        });

        KeluarMenu.setBackground(new java.awt.Color(0, 0, 0));
        KeluarMenu.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        KeluarMenu.setForeground(new java.awt.Color(255, 255, 255));
        KeluarMenu.setText("Keluar");
        KeluarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarMenuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ApplicationProject/xqp24c14 (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MemberMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainMenuLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookingMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KeluarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KetersediaanMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(MainMenuLabel)
                .addGap(26, 26, 26)
                .addComponent(BookingMenu)
                .addGap(18, 18, 18)
                .addComponent(KetersediaanMenu)
                .addGap(18, 18, 18)
                .addComponent(MemberMenu)
                .addGap(18, 18, 18)
                .addComponent(KeluarMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MemberMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberMenuActionPerformed
        // TODO add your handling code here:
        new DaftarMemberMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MemberMenuActionPerformed

    private void BookingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingMenuActionPerformed
        // TODO add your handling code here:
        new BookingMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookingMenuActionPerformed

    private void KetersediaanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KetersediaanMenuActionPerformed
        // TODO add your handling code here:
        new KetersedianMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KetersediaanMenuActionPerformed

    private void KeluarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarMenuActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeluarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingMenu;
    private javax.swing.JButton KeluarMenu;
    private javax.swing.JButton KetersediaanMenu;
    private javax.swing.JLabel MainMenuLabel;
    private javax.swing.JButton MemberMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
